apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
          # Inyección de Credenciales de BD desde el Secret
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: DB_DATABASE
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: application-secret
                key: DB_PASSWORD
