/* eslint-disable prettier/prettier */
import { DataSource, DataSourceOptions } from 'typeorm';
import {
  User,
  Rol,
  Permission,
  AsignationUserRol,
  AsignationRolPermission,
  ChainOfCustody,
  Sampling,
  Transport,
  ConfigurationVersion,
  Applicant,
  ConfigurationCalculation,
  ReportInstance,
  ReportTemplate,
  TestResult,
  ConfigurationStandard,
  ConfigurationParameter,
  ConfigurationLimit,
  ConfigurationTypeWater,
  ConfigurationUexp,
  ConfigurationTypeDagme,
  ConfigurationTypeMachine,
  ConfigurationTypeWork,
  ConfigurationUtil,
  ConfigurationCars,
  ConfigurationTypeMaterial,
  Water,
  Reported,
  Reporter,
  Register,
  Recurring,
  RegisterPicture
} from 'src/domain/shared/index.entity'; // entidades englobalizadas
import * as dotenv from 'dotenv';
dotenv.config();

export const dbdatasource: DataSourceOptions = {
  type: 'postgres',
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  entities: [
    User,
    Rol,
    Permission,
    AsignationUserRol,
    AsignationRolPermission,
    ChainOfCustody,
    Sampling,
    Transport,
    ConfigurationVersion,
    Applicant,
    ConfigurationCalculation,
    ReportInstance,
    ReportTemplate,
    TestResult,
    ConfigurationStandard,
    ConfigurationParameter,
    ConfigurationLimit,
    ConfigurationTypeWater,
    ConfigurationUexp,
    ConfigurationTypeDagme,
    ConfigurationTypeMachine,
    ConfigurationTypeWork,
    ConfigurationUtil,
    ConfigurationCars,
    ConfigurationTypeMaterial,
    Water,
    Reported,
    Reporter,
    Register,
    Recurring,
    RegisterPicture,
  ],
  synchronize: (process.env.DB_SYNCHRONIZE.toLowerCase() === 'true') ? true : false,
  //dropSchema : true,//solo usar cuando se quiera vaciar la base d edatos llenar nuevamente con seed
  logging: (process.env.DB_LOGGING.toLowerCase() === 'true') ? true : false,
};

const dataSource = new DataSource(dbdatasource)
export default dataSource
