export * from './answerQuery.interface'
export * from './rol.interface'
export * from './user.interface'
export * from './custody.interface'
export * from './sampling.interface'
export * from './transport.interface'
export * from './configurations_custody'
export * from './applicant.interface'
